name: .NET Core

on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Install dependencies
      run: dotnet restore
      working-directory: ././AdventOfCode2020
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ././AdventOfCode2020
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ././AdventOfCode2020
